### PR TITLE
FIX: Reenable parallel port triggering

### PR DESCRIPTION
**Pull request by larsoner**
@mfreilly can you try this branch on the experimental computer that will run the auditory paradigm? Once it appears to work, we should probably verify that the timing accuracy (jitter and delay) with an oscilloscope.

### CODE REVIEW

**Comment by larsoner** [comment]
@rkmaddox you might also be interested in testing this to move toward TDT independence

**Comment by rkmaddox** [comment]
Noted. Though our SPDIF solution is already in the works.

**Comment by larsoner** [comment]
Yes this would be more for if you wanted triggering during the sound stimulus (or without sound playing), e.g. to give times of visual stim flips or response windows, etc.

**Comment by rkmaddox** [comment]
Ahhh gotcha. So I could potentially use just channel 0 for sound stimulus, and then do the others with parallel port. Not a bad idea.

**Comment by larsoner** [comment]
If you want to spend $20 on a parallel port card and do some testing, feel free :)

**Pull request merged**
