### PR TITLE
FIX: Fix for new Pyglet

### PR DESCRIPTION
**Pull request by Eric89GXL**
@lkishline can you try this branch and see if it works for you?

### CODE REVIEW

**Comment by Eric89GXL** [comment]
If you forgot your `git`-fu, look here:

https://github.com/LABSN/expyfun/blob/master/git_flow.rst

But briefly, first check to see if you have my remote repo:
```
git remote -v
```
If mine is listed, great. If not, add me:
```
git remote add Eric89GXL git://github.com/Eric89GXL/expyfun.git
```
And either way, update your computer's knowledge of my remote repo:
```
git fetch Eric89GXL
```
You should see it tell you I have some new branches, including the one from this PR (`stupid-pyglet`). So create a new branch on your machine, and put it in the current state of my remote one:
```
git checkout -b stupid-pyglet Eric89GXL/stupid-pyglet
```
Then test. You can just run e.g. `examples/sync_test.py` to see if it works.

**Comment by Eric89GXL** [comment]
@lkishline also let me know if you can get to this today or Monday. We don't want to have PRs sit for too long, so if you don't have time, I'll recruit someone else to try.

**Comment by lkishline** [comment]
I'm running a tight schedule today but might have time this afternoon! If not, I'll be in this weekend and will do it then.

**Comment by lkishline** [comment]
Okay, so I've done everything and the examples/basic_experiment and stuff work. I am running the sync_test now but I am not sure what the sync_test should be doing...I have stuff flashing on my screen and such but no sound?

**Comment by Eric89GXL** [comment]
There should be clicks, but they might be quiet. You could also run
advanced_stimuli.py, that one you should definitely hear sound.

**Comment by lkishline** [comment]
Ah okay. I ran advanced_stimuli.py and got sound. (minus the fact that the hrtf didn't work but I think that is because I need to go download those angle things from that one website that I can't remember...I should do that).

**Comment by rkmaddox** [comment]
It should download them automatically, I thought?

**Comment by lkishline** [comment]
I get this:
raise ImportError('h5py could not be imported')

**Comment by rkmaddox** [comment]
Ah. Yeah, h5py is a dependency that you'll need to install. HDF5 is a
format for saving and importing data that expyfun uses (a lot like a mat
file).

**Comment by lkishline** [comment]
Ah ha! Nice to know. I was going to put in the hrtf stuff in my stim generation script today. So that saves me a lot of frustration. Thanks.

**Comment by Eric89GXL** [comment]
Yeah it should auto-download if you have `h5py` installed

**Comment by Eric89GXL** [comment]
`AppVeyor` failed because of a download problem, merging. Thanks for looking quickly @lkishline!

**Pull request merged**
