### PR TITLE
BUG: Fix video playback with other visuals

### LINKED ISSUE #358: Many problems with video presentation
So my labbies and I are having a heck of a time getting video to work. Here is a summary of the issues as I understand them, though they will fill in the rest.

0. AVBin will not play quicktime movies (we can deal with that, will just switch to x264)
1. AVBin freezes near (but not quite at) then end of our video (x264 encoded)
2. AVBin has strange image quality (Sara will post screen cap). To me it looks like a missed keyframe, but it never fixes itself. When the video is played in a media player it looks fine.

Those are the problems with trying to play a movie in pyglet. Strangely, the issues don't appear in the `simple_video` example.

Another, bigger, issue, which @drammock alluded to in #273 is that the sync may be off when playing videos. What we really need is access to the video frames and the ability to get the textures and flip as needed. This would also solve the problem of getting it in sync with the audio and triggers. Basically, we would handle video as we did in 1v2a, but instead of saucers it would be video frames. We have tried very hard to pull textures from videos in pyglet, but it is not working for us yet.

Labbies are currently signing up for github and will post more info here.

### PR DESCRIPTION
**Pull request by larsoner**
Closes #358

### CODE REVIEW

**Comment by larsoner** [comment]
@drammock this fixes a bug with video playback when other visuals are used. Can you give it a look?

**Comment by larsoner** [comment]
@LiesbethGijbels can you see if the `advanced_video.py` example works for you? In theory it should allow you to use `expyfun` video functions to show your video rather than `cv2`.

**Comment by larsoner** [comment]
@drammock can you look and try this out?

**Comment by drammock** [comment]
Not easily.  see spatialaudio/python-rtmixer#22

**Comment by drammock** [comment]
running `advanced_video.py` example on Linux looks good after installing `pillow`(which is an unstated dependency, maybe only for screenshots?).  I see the video shrinking and then moving rightward, with the background color changing behind it.  Keyboard button presses do not work to pause the video however.

**Comment by drammock** [comment]
After setting config value `RESPONSE_DEVICE` to `keyboard`, I still can't pause the video.

**Comment by larsoner** [comment]
I broke that bit of the example, it should be fixed now (pausing using 1. pauses things on my machine). If you get no keyboard response at all, perhaps try `simple_experiment.py` to see if other experiments work or not. It will tell us if the problem is specific to this example, or to `expyfun`/pyglet overall

**Comment by drammock** [comment]
hmm, button presses not working in simple_experiment either. I've probably forgotten some dumb aspect of the setup; it's been so long since I set up a new system like this.

**Comment by larsoner** [comment]
Make sure the window that pops up actually has focus, you might need to click on it to get it to really have focus

**Comment by drammock** [comment]
> you might need to click on it to get it to really have focus

yeah, I've been doing that; still no dice.

**Comment by larsoner** [comment]
Maybe try changing Pyglet versions? `pip install pyglet==1.3.2` or `pyglet<1.5` to get some 1.4 variant...?

If that doesn't work, which window manager are you running? I can try to replicate. Running just from a terminal with `python -i whatever.py` I assume?

**Comment by drammock** [comment]
downgrading to pyglet 1.4 worked!

**Pull request merged**
