### PR TITLE
MRG: doc auto-build

### PR DESCRIPTION
**Pull request by Eric89GXL**
This should get our documentation to auto-build on PRs, and auto-update to https://labsn.github.io/expyfun on merge to `master`.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
This is what this branch produces:

https://34-11614571-gh.circle-artifacts.com/0//home/ubuntu/expyfun/doc/_build/html/index.html

I'll probably have to tweak the auto-uploading once it's in `master` to get it to work properly, but at least it's building correctly.

**Comment by Eric89GXL** [comment]
Latest commit fixes flake issue, ready for review/merge from my end.

**Comment by drammock** [comment]
was just finishing reviewing, and got a new commit.  @Eric89GXL ?

**Comment by Eric89GXL** [comment]
I rebased, code is the same

**Comment by Eric89GXL** [comment]
(sorry for the confusion)

**Comment by Eric89GXL** [comment]
In case anyone is curious the doc will auto-update now:

https://labsn.github.io/expyfun/index.html

Almost as magical as magnets

**Pull request merged**
