### PR TITLE
MRG: Save and report the version

### PR DESCRIPTION
**Pull request by larsoner**
Ready for review/merge from my end.

@maddycapp27 can you look to see if you agree this would be useful?

### CODE REVIEW

**Comment by maddycapp27** [comment]
I like it. Seems like a minor change with a lot of potential to avert confusion.

**Comment by rkmaddox** [comment]
One thing I have also wondered: we write some of the parameters to the tab/log files. Shouldn't we do all of them? `stim_db`, `noise_level`, `targ_rms`, etc.? Otherwise it needs to be noted and recorded elsewhere, which defeats the purpose. These should also of course be logged when changes are made to them as well.

**Comment by rkmaddox** [comment]
Could even do `__file__` (in a `try`/`except`) so that the exact script used to generate the data file is known.

**Comment by larsoner** [comment]
Yeah we should be able to get the calling `__file__` from the stack. I'll work on adding those, setting to WIP in the meantime.

**Comment by larsoner** [comment]
Okay @rkmaddox added logging of everything

@drammock can you look, too, when you get a chance? This seems like an important missing feature

**Comment by rkmaddox** [comment]
LGTM except it still does not say which experimental file was run. Should we add that?

**Comment by larsoner** [comment]
@rkmaddox done

**Comment by rkmaddox** [comment]
Thanks. +1 for merge.

**Comment by rkmaddox** [comment]
Ping @drammock since I don't have merge privileges.

**Comment by drammock** [comment]
I'm happy with this.  tests pass locally and version is correctly reported in the stdout of `simple_experiment.py` (`Using version 2.0.0.dev0 (requested dev)`).  I made a tiny change that I'll PR into this PR momentarily; if @larsoner is happy with that he can merge this one too.

**Comment by larsoner** [comment]
Thanks for the quick reviews!

**Comment by rkmaddox** [comment]
Thanks for the addition. Makes it a much better system, especially when coming back to old data...

**Pull request merged**
