### PR TITLE
add RawImage.get_rect

### LINKED ISSUE #370: TODO: detect click on RawImage
This could either be a change in `wait_for_click_on` that allowed `RawImage` in the list of target objects, or (probably simpler) some convenience methods on `RawImage` that made it easier to spawn a transparent `Rectangle` over it (e.g., a method `get_rect` that would generate the `(x,y,w,h)` tuple needed by the `Rectangle` constructor.  (right now, `RawImage` only has a `bounds` attribute in pixels, necessitating the user to do some math)

### PR DESCRIPTION
**Pull request by drammock**
should probably add a test before merging.  Also fixes an incorrect docstring in `RawImage.bounds`

### CODE REVIEW

**Comment by larsoner** [comment]
LGTM, agreed a test would be useful

**Comment by larsoner** [comment]
@drammock okay to merge from your end?

**Comment by drammock** [comment]
yes please

**Comment by larsoner** [comment]
Thanks @drammock

**Comment by larsoner** [comment]
Rebasing #366 after this showed that there were docstring deficiencies here. They are fixed as part of #366

**Pull request merged**
