### PR TITLE
MRG: Safer dummy mode-ing

### PR DESCRIPTION
**Pull request by Eric89GXL**
@drammock can you have a look and see if you think this would have led to a more informative error, instead of silent dummy mode?

### CODE REVIEW

**Comment by drammock** [comment]
LGTM though shouldn't we add a test for the new error?

**Comment by drammock** [comment]
test fails locally:

```
======================================================================
ERROR: Test that failed TDTpy import raises ImportError
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/drmccloy/Builds/expyfun/expyfun/_utils.py", line 450, in dec
    out = function(*args, **kwargs)
  File "/home/drmccloy/Builds/expyfun/expyfun/tests/test_experiment_controller.py", line 332, in test_tdtpy_failure
    from tdt.util import connect_rpcox  # noqa, analysis:ignore
  File "/home/drmccloy/.local/lib/python2.7/site-packages/tdt/__init__.py", line 12, in <module>
    from dsp_project import DSPProject
  File "/home/drmccloy/.local/lib/python2.7/site-packages/tdt/dsp_project.py", line 1, in <module>
    from .util import connect_zbus
  File "/home/drmccloy/.local/lib/python2.7/site-packages/tdt/util.py", line 28, in <module>
    import actxobjects
  File "/home/drmccloy/.local/lib/python2.7/site-packages/tdt/actxobjects/__init__.py", line 1, in <module>
    from RPcoX import RPcoX
  File "/home/drmccloy/.local/lib/python2.7/site-packages/tdt/actxobjects/RPcoX.py", line 1
SyntaxError: encoding problem: mbcs

----------------------------------------------------------------------
```

**Comment by Eric89GXL** [comment]
@drammock that is actually a bug with TDTpy, it should raise an `ImportError` if you try to import it on a non-Windows system

**Comment by Eric89GXL** [comment]
...actually it should refuse to install in the first place

**Comment by drammock** [comment]
hmm, I'd rather have TDTpy raise ImportError on non-Windows rather than refuse to install altogether.; seems like it would be easier to change back if TDT ever supports linux.

**Comment by Eric89GXL** [comment]
> seems like it would be easier to change back if TDT ever supports linux.

Right now the backbone of TDTpy is using ActiveX, a Windows-only technology. So any Linux-izing will require a decent amount of recoding for the TDTpy codebase. So I don't think allowing it to install now would actually make it any easier.

**Comment by drammock** [comment]
oh, right.  duh.

**Comment by drammock** [comment]
I suspect the AppVeyor fail is due to `tdtpy` vs `TDTPy`, BTW

**Comment by Eric89GXL** [comment]
```
larsoner@bunk:~/Documents/python/expyfun$ pip install --user tdtpy
Collecting tdtpy
  Downloading TDTPy-0.7.2.zip (378kB)
    100% |████████████████████████████████| 378kB 2.1MB/s 
```
So it at least tries to go on my system, I'm going to run it without the `-q` to see the log

**Comment by Eric89GXL** [comment]
@drammock test added and the CIs are happy, feel free to merge if you're happy with it

**Comment by drammock** [comment]
thanks @Eric89GXL

**Pull request merged**
