### PR TITLE
FIX: Fix recon

### PR DESCRIPTION
**Pull request by larsoner**
@rkmaddox @maddycapp27 because trackers are identified by their memory location, it is actually possible for tracker names to repeat in the unlucky case where the same memory address is used by multiple trackers (e.g., one is instantiated after another is garbage collected). I hit such a use case recently. This fixes the reconstruction.

Should we also fix the naming, e.g. by also tagging with the time of instantiation (to the millisecond), too?

### CODE REVIEW

**Comment by larsoner** [comment]
@maddycapp27 any thoughts on this one?

**Comment by maddycapp27** [comment]
@larsoner Sorry for the delay! I don't see any harm in tagging with more info but you would be a better judge. Could the time tag replace the ID number or would it be another data line?

**Comment by rkmaddox** [comment]
If time is only recorded to the millisecond, then we still ned the other id. It's entirely possible that two trackers could be created during the same millisecond.

**Comment by larsoner** [comment]
I'm thinking both time and id

**Comment by larsoner** [comment]
Turns out `time.time()` is good to the microsecond, but I still made it use `id-time` now instead of just `id`.

Okay with you @rkmaddox @maddycapp27 ?

**Comment by maddycapp27** [comment]
Sounds good to me

**Comment by larsoner** [comment]
@drammock do you have time to look?

**Comment by drammock** [comment]
I can review later this morning.

**Comment by drammock** [comment]
tests pass in both py2 and py3 on my Linux, and both `tracker_dealer.py` and `tracker_dealer_doublesided.py` examples work.  Only thing that sticks out at me is that the example scripts don't end with a `plt.show()`.  The tracker IDs in the verbose output are annoyingly long to identify by eye, but at least they won't collide now.

**Comment by larsoner** [comment]
Thanks for the quick look @drammock

**Comment by rkmaddox** [comment]
Not to beat a dead horse, but if we wanted to ensure uniqueness, but also make them more readable, we could hash the id-time tag.

**Comment by larsoner** [comment]
+1 by me once someone is motivated to do it (i.e., not a high priority)

**Comment by rkmaddox** [comment]
For whomever does it in the future:

```python
import hashlib

hashlib.md5('foo').hexdigest()
# outputs 'acbd18db4cc2f85cedef654fccc4a4d8'
hashlib.md5('fool').hexdigest()
# outputs 'dd7b696b96434d2bf07b34f9c125d51d'
```

**Comment by drammock** [comment]
I thought of that too, but I didn't think that md5 hashes were much of an
improvement in readability... probably somewhat quicker to make the "are
these two different" judgement at a glance, but still hard to make the "is
this the same one I was looking at several seconds ago?" judgement.

**Comment by rkmaddox** [comment]
Agree, though it would at least allow eyeballing that wouldn't depend on the last few characters.

If we are OK with one in 4.3 billion chance of collision: https://github.com/zacharyvoase/humanhash.

**Pull request merged**
