### PR TITLE
ENH: Allow larger arrays

### PR DESCRIPTION
**Pull request by Eric89GXL**
Simple enhancement to allow > 2D arrays for dprime calculation (along last axis).

### CODE REVIEW

**Comment by rkmaddox** [comment]
Tests :-(

**Comment by Eric89GXL** [comment]
They are implicitly tested by the existing tests, but I'll add one or two more.

**Comment by Eric89GXL** [comment]
@rkmaddox done

**Comment by rkmaddox** [comment]
Sorry, meant tests failed.

**Comment by rkmaddox** [comment]
Looks good to me otherwise.

**Comment by Eric89GXL** [comment]
I have been waiting a couple of hours for the AppVeyor build to complete, which is too long. The problem is that the builds are serial (on Travis they are parallel time-permitting), so it takes a long time with multiple commits. I added a commit to just test one case on Windows, 64-bit Python3.4 for simplicity.

**Comment by Eric89GXL** [comment]
Okay @rkmaddox finally ready for merge

**Comment by rkmaddox** [comment]
Thanks for the change.

**Pull request merged**
