### PR TITLE
ENH: Add SOUND_CARD_TRIGGER_INSERTION

### PR DESCRIPTION
**Pull request by larsoner**
Allows `"SOUND_CARD_TRIGGER_INSERTION": "append"` instead of the default `"prepend"`.

### CODE REVIEW

**Comment by larsoner** [comment]
Reported by end-users as working. @drammock did you want to take a quick look?

**Comment by drammock** [comment]
looks reasonable to me. Checking my understanding of the code: this allows the extra sound card channel that's being used for triggers to come after the audio channels instead of before, right?

**Comment by larsoner** [comment]
Yes indeed

**Comment by drammock** [comment]
tx @larsoner

**Comment by rkmaddox** [comment]
Thanks!

**Pull request merged**
