### PR TITLE
FIX: fix typo

### PR DESCRIPTION
**Pull request by maddycapp27**
fix a typo in rtmixer docs

### CODE REVIEW

**Comment by drammock** [comment]
There's another typo on line 593 of experiment controller, backgound -> background, which is causing Travis to fail. Can you fix that too? (I'm writing from phone so I can't do it myself at the moment)

**Comment by drammock** [comment]
@larsoner looks like we're still running [a travis test in a py2.7 environment](https://travis-ci.org/LABSN/expyfun/jobs/541865658), and anything in `expyfun` that depends on `mne` is now failing.  Do we need to continue supporting 2.7 for some reason?  I thought it was the EyeLink `pylink` module, but they have py3k versions of that now...

**Comment by larsoner** [comment]
Probably no need to support 2.7 anymore, especially given our versioning system. Okay with you @rkmaddox @maddycapp27 to go 3.5+ only?

**Comment by maddycapp27** [comment]
I'm fine with it --  my computer and the research computers are either transitioned or imminently will transition. @rkmaddox Here's some more motivation to update your computer :)

**Comment by larsoner** [comment]
Thanks @maddycapp27

**Pull request merged**
