### PR TITLE
MRG: Check spelling

### PR DESCRIPTION
**Pull request by larsoner**
The ultimate pedantic PR.

But really I just want to see if someone other than @maddycapp27 opening a PR will trigger CircleCI.

### CODE REVIEW

**Comment by larsoner** [comment]
Of course it does. @maddycapp27 when you disabled CircleCI building for your fork, did you actually delete it on CircleCI, or just remove the webhook using the GitHub interface? I'm guessing it was the latter, but if you delete / remove continuous integration for your fork it should make it work properly.

**Comment by larsoner** [comment]
@maddycapp27 if you have time to take a quick look please do, then I'll merge

**Comment by maddycapp27** [comment]
I support proper spelling :) 

I looked at circleci and was able to revoke its permissions to my github but not to delete the integration. I'm not sure if that's enough.

**Comment by larsoner** [comment]
Thanks for the look @maddycapp27, we'll see on the CircleCI issue on your next PR :)

**Pull request merged**
