### PR TITLE
WIP, ENH: Add CRM corpus stimuli

### PR DESCRIPTION
**Pull request by rkmaddox**
Very much a work in progress--not sure the best way to include this in the main repo. Particularly what to do with the data. It should ship with sampling rates of 24414 and 44100, but I am not sure what to do when someone uses the prepare corpus functionality at a different sampling rate.

### CODE REVIEW

**Comment by rkmaddox** [comment]
@Eric89GXL would be good if we could gchat about this at some point. There are different ways a lot of this could be implemented. There is also a lot of cleaning up and error checking to add to make it generally usable.

**Comment by rkmaddox** [comment]
Regarding data prep, maybe the best thing to do is only store the original raw binary files and have people prepare the corpus in the local experiment directory each time.

**Comment by Eric89GXL** [comment]
How big is the complete corpus (MB/GB)? How long does it take to generate (minutes/hours)? Gotta find that download vs processing time tradeoff sweet spot. We can make the prepared/complete one (plus the script that made it from raw files) available if we need to.

**Comment by rkmaddox** [comment]
The original corpus is 300 MB at 40 kHz. The 44100 corpus is 325 and took 28 minutes to make using 11 cores on my machine (it's a looooot of resampling), though that was using scipy's resample function and not expyfun's (which is private--should we have a public one?). So the 24414 corpus would be about 180 MB. Even if it takes an hour to process, it's set it and forget it, so it doesn't seem like it would be that big a hindrance. We could also put 44100 and 24414 versions on Lester and people could manually download those if they wanted to.

So I think I propose: only distribute the raw binary corpus with expyfun, and have people prepare (or download) their own resampled versions to be stored locally with each experiment. I am not a strong proponent of any plan, however.

**Comment by Eric89GXL** [comment]
The resampling should actually be much faster if you use `expyfun`'s, since it *should* make use of `mne` which in turn can use CUDA.

I'm fine just putting the raw data up there, don't have a strong opinion either way.

**Comment by drammock** [comment]
I don't think we should assume that all users are CUDA-savvy (e.g., might
be on laptop), and hence providing either (1) downloads at the two
different fs rates, and/or (2) a very clear readme that explains what to
expect from scipy vs expyfun/mne is needed.

The resampling should actually be much faster if you use expyfun's, since
it *should* make use of mne which in turn can use CUDA.

I'm fine just putting the raw data up there, don't have a strong opinion
either way.

—
Reply to this email directly or view it on GitHub
<https://github.com/LABSN/expyfun/pull/247#issuecomment-135128771>.

**Comment by rkmaddox** [comment]
expyfun's resampling does not use CUDA. It took 28 minutes, exactly the same as scipy's resampling. But actually, parallelizing it by stimulus file, rather than doing one file with `n_jobs` > 1, is substantially faster anyway. So it's possible CUDA may speed it up, but I think it's more likely this is as fast as it's going to be until Eric implements polyphase resampling in scipy.

**Comment by drammock** [comment]
I thought expyfun used mne for resampling (and therefore CUDA) when present
and properly configured?

**Comment by rkmaddox** [comment]
Nope, it uses its own version that is based on mne (copied from an old version of mne?).

**Comment by Eric89GXL** [comment]
@rkmaddox are you un-busy enough to pick this back up? (hahahaha)

**Comment by rkmaddox** [comment]
Hahahaha. I think I left it in a state where it works, as in you could get
the CRM sounds you need. But I wanted it to get to the point where it was a
nice CRM class that got instantiated and handled everything for you.

Maybe the former is a good enough state to include, then we can keep that
functionality and add a nice CRM class alongside eventually?

--
Ross Maddox, Ph.D.
Postdoctoral Fellow
Institute for Learning & Brain Sciences
University of Washington
phone: 206-685-4662
http://faculty.washington.edu/rkmaddox/

**Comment by Eric89GXL** [comment]
Yeah we can do it bit-by-bit, stimuli first, then paradigm codeblock later.

**Comment by Eric89GXL** [comment]
Closing for now, we can resurrect once someone finds time to refactor, etc.

**Comment by rkmaddox** [comment]
Sure. I am sure I (or my student) will be the one to reopen it. I also have the adaptive track code to put in here. Hopefully someone needs that before I do so they have to do it.

**Comment by rkmaddox** [comment]
Well, that time has come and I finally need the CRM functionality. I assume new PR is the way to do it?

Will I need to rebase? I've never done that.

**Comment by rkmaddox** [comment]
@Eric89GXL @drammock just in case you don't get pinged for comments on closed PRs.

**Comment by Eric89GXL** [comment]
Yes ideally you would rebase. I'd recommend setting up "meld" as your diff
viewer before doing it.

If it goes horribly wrong, you can cut your losses and make a new branch
based on upstream master and copy paste your changes.

**Comment by rkmaddox** [comment]
Hmm. I successfully rebased. Then I tried to push. It didn't work, and the forums told me to force push. So I did, but now I cannot reopen the PR because it was force pushed. Should I open a new PR?

**Comment by rkmaddox** [comment]
Ah, from reading it seems like it might just be a privileges thing.

**Comment by rkmaddox** [comment]
It also appears the rebase may not have gone right, since I now can't import ``expyfun.analyze``. I'll keep trying to figure it out.

**Comment by rkmaddox** [comment]
FYI, I've rebased and gotten it to a point where I think it is sufficiently functional and documented. That has happened on my `rkmaddox:crm` branch, which is not showing up on this PR since it is closed.

**Comment by drammock** [comment]
I can't seem to reopen it either... The button is greyed out.

**Comment by rkmaddox** [comment]
Ok. I'm out today, but it seems like the thing to do is just open a new PR.

**Pull request closed without merging**
