### PR TITLE
update install docs; silence doc build warning

### LINKED ISSUE #434: cannot pip install expyfun
- https://pypi.org/project/expyfun/ is currently a 404
- searching https://pypi.org/search/?q=expyfun yields no results
- `pip install expyfun` yields `ERROR: Could not find a version that satisfies the requirement expyfun (from versions: none) ERROR: No matching distribution found for expyfun`

### PR DESCRIPTION
**Pull request by drammock**
closes #434

### CODE REVIEW

**Comment by drammock** [comment]
circle fails with 
```
E: Failed to fetch http://deb.debian.org/debian/pool/main/libs/libsndfile/libsndfile1_1.0.28-6_amd64.deb  404  Not Found [IP: 146.75.30.132 80]
```

**Comment by larsoner** [comment]
Probably needs a `sudo apt update` before any `sudo apt install` call (and `apt-get` should be changed to `apt` if it hasn't already)

**Review by larsoner — APPROVED** [review]
feel free to self-merge until green

**Comment by drammock** [comment]
notes for my future self: CI failures now are this:
```
___________ ERROR collecting expyfun/_sound_controllers/_pyglet.py ____________
C:\Users\VssAdministrator\AppData\Roaming\Python\Python37\site-packages\pyglet\media\codecs\wmf.py:836: in __init__
    ole32.CoInitializeEx(None, COINIT_MULTITHREADED)
_ctypes/callproc.c:935: in GetResult
    ???
E   OSError: [WinError -2147417850] Cannot change thread mode after it is set
```

I did some poking around and it looks like current main of pyglet catches this error and converts it to a warning:

https://github.com/pyglet/pyglet/blob/d1876a9415bb51a59c2248f7d5ecd74b81d9638b/pyglet/media/codecs/wmf.py#L834-L838

added [here](https://github.com/pyglet/pyglet/commit/2f730bf340e30b7d74d9f03e682996d11c3d5f55) (april 2020) and it should be in pyglet 1.5.4 and above (windows py37 CI installs pyglet 1.5.21 so I'm confused as to why we're seeing this error)

**Comment by larsoner** [comment]
Thanks @drammock !

**Pull request merged**
